<?php
namespace wscvua\ServerTime;

use yii\web\AssetBundle;

class ServerTimeAsset extends AssetBundle
{
    public $sourcePath = '@common/widgets/ServerTime';

    public $js = [
        'server-time.js'
    ];

    public $depends = [
        'yii\web\JqueryAsset'
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}